[window]
startup_mode = "Maximized"
# opacity = 0.8

[font]
size = 14
normal = {family = "Hack Nerd Font Propo", style = "Regular"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
